# Site settings
title: Eddie's Blog
email: eblundell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eblundell.com" # the base hostname & protocol for your site
twitter_username: wetbeard
github_username:  eddie

# Build settings
markdown: kramdown


assets:
  sources:
    - _assets/styles
    - _assets/scripts
    - _assets/images

