# Site settings
title: Mouki 盲亀
email: eblundell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts from a Web Developer who loves Studying Japanese, Productivity and Tea, constantly looking for more time in the day..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eblundell.com" # the base hostname & protocol for your site
twitter_username: moukiio
github_username:  eddie

# Build settings
markdown: kramdown

assets:
  sources:
    - _assets/styles
    - _assets/scripts
    - _assets/images

